name: finalproject
description: Final Project for Mobile Development
publish_to: none
environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  bloc_concurrency: ^0.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  http: ^0.13.0
  equatable: ^2.0.3
  stream_transform: ^2.0.0
  web_socket_channel: ^1.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.2.0
  mocktail: ^0.2.0

flutter:
  uses-material-design: true
